services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:2.11.3'
    container_name: npm
    dns:
      - 192.168.0.19
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data/npm_data:/data
      - ./data/npm_letsencrypt:/etc/letsencrypt
      - ./data/npm_logs:/var/log/nginx
    networks:
      - homelab_network

networks:
  homelab_network:
    external: true