services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - HARDCOVER_TOKEN
      - NETWORK_SHARE_MODE=false
      - CWA_PORT_OVERRIDE=8083
    volumes:
      - ./data/config:/config
      - /Volumes/Elements/homelab/calibre-web/import:/cwa-book-ingest
      - /Volumes/Elements/homelab/calibre-web/library:/calibre-library
    ports:
      - 8083:8083
    restart: unless-stopped

networks:
  homelab_network:
    external: true